#! /bin/bash
#
# jenkins	Start/Stop the Jenkins Continuous Integration server.
#
# chkconfig: 345 91 10
# description: Jenkins is a Continuous Integration server. \
#              It monitors a source code repository and triggers builds \
#              when it detects any changes. See https://jenkins.dev.java.net/ \
#              for more details.
# processname: jenkins
# pidfile: /var/run/jenkins.pid


# Source function library.
. /etc/rc.d/init.d/functions

# Get config.
. /etc/sysconfig/network

# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 0

startup=/opt/jenkins/bin/start-jenkins.sh
shutdown=/opt/jenkins/bin/stop-jenkins.sh
export JAVA_HOME=/usr/java/default
JENKINS_USER=jenkins

start(){
 echo -n $"Starting Jenkins service: "
 su - $JENKINS_USER -c $startup
 RETVAL=$?
 echo
}

stop(){
 action $"Stopping Jenkins service: "
 su - $JENKINS_USER -c $shutdown
 RETVAL=$?
 echo
}

status(){
 numproc=`ps -ef | grep jenkins.war | grep -v "grep jenkins.war" | wc -l`
 if [ $numproc -gt 0 ]; then
  echo "Jenkins is running..."
  else
  echo "Jenkins is stopped..."
 fi
}

restart(){
  stop
  start
}


# See how we were called.
case "$1" in
start)
 start
 ;;
stop)
 stop
 ;;
status)
 status
 ;;
restart)
 restart
 ;;
*)
 echo $"Usage: $0 {start|stop|status|restart}"
 exit 1
esac

exit 0
