#!/bin/sh
#
# /etc/init.d/zookeeper
# Subsystem file for "ZooKeeper" server
#
# chkconfig:  2345 95 05	
# description: ZooKeeper server daemon
#
# processname: zookeeper
# config: /opt/zookeeper/zookeeper-3.4.3/conf/zoo.cfg
# pidfile: /zookeeper_data/zookeeper_server.pid

# source function library
. /etc/rc.d/init.d/functions

# pull in sysconfig settings
[ -f /etc/sysconfig/zookeeper ] && . /etc/sysconfig/zookeeper

RETVAL=0
prog="ZooKeeper"
ZOOKEEPER_INSTALL=/opt/zookeeper/zookeeper-3.4.3

start() {	
	echo -n $"Starting $prog:"
	$ZOOKEEPER_INSTALL/bin/zkServer.sh start
	RETVAL=$?
	[ "$RETVAL" = 0 ] && touch /var/lock/subsys/$prog
	echo
}

stop() {	
	echo -n $"Stopping $prog:"
	$ZOOKEEPER_INSTALL/bin/zkServer.sh stop
	killproc $prog -TERM
	RETVAL=$?
	[ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
	echo
}

reload() {	
	echo -n $"Reloading $prog:"
	killproc $prog -HUP
	RETVAL=$?
	echo
}

case "$1" in	
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	reload)
		reload
		;;
	condrestart)
		if [ -f /var/lock/subsys/$prog ] ; then
			stop
			# avoid race
			sleep 3
			start
		fi
		;;
	status)
		status $prog
		RETVAL=$?
		;;
	*)	
		echo $"Usage: $0 {start|stop|restart|reload|condrestart|status}"
		RETVAL=1
esac
exit $RETVAL
